using CookieBook.Infrastructure.DTO.Base;
using System;
using System.Collections.Generic;
using System.Text;

namespace CookieBook.Infrastructure.DTO.Admin
{
    public class AdminDto : AccountDto
    {
        /// <summary>
        /// Admin login, generated by the system, used for login
        /// </summary>
        /// <example>2a85Bo978K1</example>
        public string Login { get; set; }
    }
}